#+title: dMRI Validation
#+ROAM_TAGS: "AINOSTICS"

* dMRI Validation Lit Review
This is a literature review for AINOSTICS on the use and validation of dMRI microstructure imaging techniques.

** Validation of microstructure techniques
The idea of this section is building a case for diffusion imaging and how the observed signal or the resulting maps/models relate to cellular biology and what is driving the signal being acquired. This can include work with synthetic, digital and tissue phantoms; animal and histology studies, etc.

*** List of papers
- [[file:dyrby2018.org][Dyrby, T. B.: Validation strategies for the interpretation of microstructure imaging using diffusion MRI]]

** Application/added value of dMRI techniques
The idea of this section is how diffusion imaging derived parameters have been shown to offer value in diagnosing neurological conditions (with a focus on neurodegeneration), and any validation work around this.

*** List of papers
- [[file:kamiya2020.org][Kamiya, K., Hori, M., & Aoki, S.: NODDI in clinical research]]
- [[file:weston2015.org][Weston, P. S., Simpson, I. J., Ryan, N. S., Ourselin, S., & Fox, N. C.: Diffusion imaging changes in grey matter in Alzheimer's disease: a potential marker of early neurodegeneration]]
